routingRules:
  - version: "2.0.0"
    targetType: "url"
    target:
      url: "http://sandbox-bap:3001/api/bap-webhook"
    endpoints:
      - on_discover
      - on_select
      - on_init
      - on_confirm
      - on_status
      - on_update
      - on_cancel
