routingRules:
  - version: "2.0.0"
    targetType: "bpp"
    endpoints:
      - select
      - init
      - confirm
      - status
      - track
      - cancel
      - update
      - rating
      - support

  - version: "2.0.0"
    targetType: "url"
    target:
      url: "https://34.93.141.21.sslip.io/beckn" #test CDS URL
    endpoints:
      - discover
