routingRules:
  - version: "2.0.0"
    targetType: "bap"
    endpoints:
      - on_init  # response to cascaded init from P2P Trading BPP
      - on_confirm  # response to cascaded confirm from P2P Trading BPP
      - on_update  # update sent to P2P Trading BPP after fulfillment


